// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 工程报备车辆表
type EcdFileVehicle struct {
	// ID
	ID int64 `json:"id"`
	// 工程报备车辆表ID
	FileVehicleID string `json:"file_vehicle_id"`
	// 报备主表ID
	FileMainID string `json:"file_main_id"`
	// 车辆ID
	VehicleID *string `json:"vehicle_id"`
	// 审核状态
	CheckStatus *int `json:"check_status"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 创建人
	CreateBy *string `json:"create_by"`
	// 更新时间
	UpdateAt *time.Time `json:"update_at"`
	// 更新人
	UpdateBy *string `json:"update_by"`
	// 删除时间
	DeleteAt *time.Time `json:"delete_at"`
	// 删除人
	DeleteBy *string `json:"delete_by"`
	// 是否删除
	IsDelete bool `json:"is_delete"`
}
