// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 工程报备-采集位置信息点
type EcdFileLinePoint struct {
	// ID
	ID int64 `json:"id"`
	// 工程报备采集位置信息点ID
	LinePointID string `json:"line_point_id"`
	// 报备主表ID
	FileMainID string `json:"file_main_id"`
	// gps位置点
	GpsPoint *string `json:"gps_point"`
	// 地图位置点
	MapPoint *string `json:"map_point"`
	// 信息点名称
	LinePointName *string `json:"line_point_name"`
	// 信息点备注
	LinePointRemark *string `json:"line_point_remark"`
	// 信息点类型 0停车点 1起点 2终点 3修车点
	PointType *int `json:"point_type"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人
	CreatedBy *string `json:"created_by"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at"`
	// 更新人
	UpdatedBy *string `json:"updated_by"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人
	DeletedBy *string `json:"deleted_by"`
	// 是否删除
	IsDeleted bool `json:"is_deleted"`
}
