// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 车辆夜晚行驶记录
type VehicleNightTravelRecord struct {
	// ID
	ID int64 `json:"id"`
	// 车辆夜晚运行记录ID
	RecordID string `json:"record_id"`
	// 车辆ID
	VehicleID string `json:"vehicle_id"`
	// 所属企业ID
	EnterpriseID string `json:"enterprise_id"`
	// 运输路线ID
	Route *string `json:"route"`
	// 运营商ID
	SprgID *string `json:"sprg_id"`
	// 车辆类型
	VehicleType *int `json:"vehicle_type"`
	// 营运类型
	ServiceType *int `json:"service_type"`
	// 接驳开始时间
	RecordStartTime *time.Time `json:"record_start_time"`
	// 接驳结束时间
	RecordEndTime *time.Time `json:"record_end_time"`
	// 状态(1生效2未审核3审核不通过)
	Status *int `json:"status"`
	// 审核不通过原因
	Cause *string `json:"cause"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 创建人
	CreateBy *string `json:"create_by"`
	// 更新时间
	UpdateAt *time.Time `json:"update_at"`
	// 更新人
	UpdateBy *string `json:"update_by"`
	// 删除时间
	DeleteAt *time.Time `json:"delete_at"`
	// 删除人
	DeleteBy *string `json:"delete_by"`
	// 是否删除
	IsDelete bool `json:"is_delete"`
	// 备注
	Remark *string `json:"remark"`
}
