// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 企业扣分日志表
type EnterpriseScoreLog struct {
	// ID
	ID int64 `json:"id"`
	// 企业扣分日志表ID
	LogID string `json:"log_id"`
	// 企业ID
	EnterpriseID string `json:"enterprise_id"`
	// 当前分数
	CurrentScore int `json:"current_score"`
	// 扣分分值
	AddScore int `json:"add_score"`
	// 扣分内容
	Content string `json:"content"`
	// 相关文件url
	FileURL string `json:"file_url"`
	// 扣分项ID
	ScoreSetID string `json:"score_set_id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人
	CreatedBy *string `json:"created_by"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at"`
	// 更新人
	UpdatedBy *string `json:"updated_by"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人
	DeletedBy *string `json:"deleted_by"`
	// 是否删除
	IsDeleted bool `json:"is_deleted"`
}
