// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 指纹表
type FingerprintInformation struct {
	// ID
	ID int64 `json:"id"`
	// 指纹表ID
	FingerprintInformationID string `json:"fingerprint_information_id"`
	// 用户ID
	UserID *string `json:"user_id"`
	// 车辆ID
	VehicleID *string `json:"vehicle_id"`
	// sim卡ID
	SimID *string `json:"sim_id"`
	// 指令ID
	MessageID *string `json:"message_id"`
	// 操作类型
	OperationType *int `json:"operation_type"`
	// 内容
	Content *string `json:"content"`
	// 是否成功
	IsSuccess *bool `json:"is_success"`
	// 操作时间
	OperationTime *time.Time `json:"operation_time"`
	// 上传时间
	UploadTime *time.Time `json:"upload_time"`
	// 时间戳
	SaveID *string `json:"save_id"`
	// 驾驶员ID
	DriverID *string `json:"driver_id"`
	// 驾驶员姓名
	DriverName *string `json:"driver_name"`
	// 指纹ID
	FingerID *string `json:"finger_id"`
	// 终端ID
	TerminalID *string `json:"terminal_id"`
}
