// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// SIM卡
type SimCard struct {
	// ID
	ID int64 `json:"id"`
	// SIM卡ID
	SimCardID string `json:"sim_card_id"`
	// 所属部门ID
	DeptID *string `json:"dept_id"`
	// 绑定终端ID
	TerminalID *string `json:"terminal_id"`
	// 代理商ID
	ProxyrgID *string `json:"proxyrg_id"`
	// 运营商ID
	OperatorsID *string `json:"operators_id"`
	// SIM卡号
	SimNumber *string `json:"sim_number"`
	// 运营商类型
	MobileType *int `json:"mobile_type"`
	// 备注
	Remark *string `json:"remark"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人
	CreatedBy *string `json:"created_by"`
	// 修改时间
	UpdatedAt *time.Time `json:"updated_at"`
	// 修改人
	UpdatedBy *string `json:"updated_by"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人
	DeletedBy *string `json:"deleted_by"`
	// 是否删除
	IsDeleted bool `json:"is_deleted"`
	// sim卡来源，1-平台，2-其他平台
	Source *int `json:"source"`
}
