// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// sim卡管理（外部来源）
type SimCardAll struct {
	// ID
	ID int64 `json:"id"`
	// SIM卡管理（外部来源）ID
	SimcardAllID string `json:"simcard_all_id"`
	// 车牌号码
	PlateNumber *string `json:"plate_number"`
	// 车牌号码
	PlateColor *string `json:"plate_color"`
	// 所在部门ID
	DeptID *string `json:"dept_id"`
	// 代理商ID
	ProxyrgID *string `json:"proxyrg_id"`
	// 所在企业ID
	EnterpriseID *string `json:"enterprise_id"`
	// sim卡号
	SimNumber *string `json:"sim_number"`
	// 服务费到期时间
	ServiceEndTime *time.Time `json:"service_end_time"`
	// 终端ID
	TerminalID *string `json:"terminal_id"`
	// 应用于何种系统
	SystemName *string `json:"system_name"`
	// sim卡类型
	SimType *int `json:"sim_type"`
	// 用户ID
	UserID *string `json:"user_id"`
	// 运营商类型
	MobileType *int `json:"mobile_type"`
	// 解绑原因
	UpdateCause *string `json:"update_cause"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 创建人
	CreateBy *string `json:"create_by"`
	// 更新时间
	UpdateAt *time.Time `json:"update_at"`
	// 更新人
	UpdateBy *string `json:"update_by"`
	// 删除时间
	DeleteAt *time.Time `json:"delete_at"`
	// 删除人
	DeleteBy *string `json:"delete_by"`
	// 是否删除
	IsDelete bool `json:"is_delete"`
	// 备注
	Remark *string `json:"remark"`
}
