// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 终端类型
type TerminalTypes struct {
	// ID
	ID int64 `json:"id"`
	// 终端类型ID
	TypeID string `json:"type_id"`
	// 终端类型
	ProtocolName string `json:"protocol_name"`
	// 备注
	Remark *string `json:"remark"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 创建人
	CreateBy *string `json:"create_by"`
	// 修改时间
	UpdateAt *time.Time `json:"update_at"`
	// 修改人
	UpdateBy *string `json:"update_by"`
	// 删除时间
	DeleteAt *time.Time `json:"delete_at"`
	// 删除人
	DeleteBy *string `json:"delete_by"`
	// 是否删除
	IsDelete bool `json:"is_delete"`
}
