// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type TerminalCheck struct {
	// ID
	ID int64 `json:"id"`
	// 车辆达标情况ID
	TerminalCheckID string `json:"terminal_check_id"`
	// 终端ID
	TerminalID string `json:"terminal_id"`
	// acc状态
	Acc *string `json:"acc"`
	// 制动信号（刹车）
	Brake *string `json:"brake"`
	// 左转向灯信号
	LeftLamp *string `json:"left_lamp"`
	// 右转向灯信号
	RightLamp *string `json:"right_lamp"`
	// 近光灯信号
	NearLamp *string `json:"near_lamp"`
	// 远光灯信号（大灯）
	FarLamp *string `json:"far_lamp"`
	// 喇叭信号
	LoudSpeaker *string `json:"loud_speaker"`
	// 倒挡信号
	Reverse *string `json:"reverse"`
	// 定位状态
	Locate *string `json:"locate"`
	// 前门
	FrontDoor *string `json:"front_door"`
	// 中门
	MiddleDoor *string `json:"middle_door"`
	// 后门
	BackDoor *string `json:"back_door"`
	// gps信号
	GpsOpen *string `json:"gps_open"`
	// 北斗信号
	BdOpen *string `json:"bd_open"`
	// 语音播报器
	VoiceDevice *string `json:"voice_device"`
	// 摄像头
	Camera *string `json:"camera"`
	// 紧急报警按钮
	EmergencyAlarm *string `json:"emergency_alarm"`
	// 里程数
	Mileage *string `json:"mileage"`
	// 油量
	Oilmass *string `json:"oilmass"`
	// 车速
	VehicleSpeed *string `json:"vehicle_speed"`
	// 主电源掉电报警
	PowerAlarm *string `json:"power_alarm"`
	// 是否通过
	Pass *string `json:"pass"`
	// 空调
	AirConditioning *string `json:"air_conditioning"`
	// 自动车速保存
	AutoVehicleSpeed *string `json:"auto_vehicle_speed"`
	// 是否北斗国标脉冲信号
	IsImpulseSpeed bool `json:"is_impulse_speed"`
	// 故障截止时间
	FaultEndTime *time.Time `json:"fault_end_time"`
	// 视频情况
	VideoPass *string `json:"video_pass"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 创建人
	CreateBy *string `json:"create_by"`
	// 更新时间
	UpdateAt *time.Time `json:"update_at"`
	// 更新人
	UpdateBy *string `json:"update_by"`
	// 删除时间
	DeleteAt *time.Time `json:"delete_at"`
	// 删除人
	DeleteBy *string `json:"delete_by"`
	// 是否删除
	IsDelete bool `json:"is_delete"`
}
