// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 终端采购单
type TerminalBuyBill struct {
	// ID
	ID int64 `json:"id"`
	// 终端采购单ID
	BillID string `json:"bill_id"`
	// 终端类型
	TerminalType int `json:"terminal_type"`
	// s/n起号
	StartSn *int64 `json:"start_sn"`
	// s/n止号
	EndSn *int64 `json:"end_sn"`
	// 采购人
	BuyerID *string `json:"buyer_id"`
	// 采购日期
	BuyDate *time.Time `json:"buy_date"`
	// 终端数
	SnCount *int64 `json:"sn_count"`
	// 用掉的终端数
	UseSnCount *int64 `json:"use_sn_count"`
	// 终端数是否用完
	IsSnUseOver bool `json:"is_sn_use_over"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人
	CreatedBy *string `json:"created_by"`
	// 修改时间
	UpdatedAt *time.Time `json:"updated_at"`
	// 修改人
	UpdatedBy *string `json:"updated_by"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人
	DeletedBy *string `json:"deleted_by"`
	// 是否删除
	IsDeleted bool `json:"is_deleted"`
	// 备注
	Remark *string `json:"remark"`
}
