// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 终端参数配置项
type TerminalParamItem struct {
	// ID
	ID int64 `json:"id"`
	// 终端参数配置项ID
	ParamItemID string `json:"param_item_id"`
	// 参数项名称
	ParamItemName string `json:"param_item_name"`
	// 参数类型
	ParamTypeID string `json:"param_type_id"`
	// 数据类型
	DataType int `json:"data_type"`
	// 是否枚举
	IsEnum bool `json:"is_enum"`
	// 是否含有子参数
	HasSubparam bool `json:"has_subparam"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人
	CreatedBy *string `json:"created_by"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at"`
	// 更新人
	UpdatedBy *string `json:"updated_by"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人
	DeletedBy *string `json:"deleted_by"`
	// 是否删除
	IsDeleted bool `json:"is_deleted"`
	// 备注
	Remark *string `json:"remark"`
	// 枚举关联字典ID
	DictID *string `json:"dict_id"`
}
