// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 子参数明细配置信息
type TerminalParamSub struct {
	// ID
	ID int64 `json:"id"`
	// 自参数ID
	ParamSubID string `json:"param_sub_id"`
	// 参数配置项ID
	ParamID string `json:"param_id"`
	// 起始比特位
	BitStart int64 `json:"bit_start"`
	// 结束比特位
	BitEnd int64 `json:"bit_end"`
	// 子参数名称
	ParamSubName string `json:"param_sub_name"`
	// 是否是枚举
	IsEnum bool `json:"is_enum"`
	// 枚举关联字典ID
	EnumDictID *string `json:"enum_dict_id"`
	// 参数值
	ParamValue *string `json:"param_value"`
	// 添加时间
	CreateAt time.Time `json:"create_at"`
	// 添加人
	CreateBy *string `json:"create_by"`
	// 更新时间
	UpdateAt *time.Time `json:"update_at"`
	// 更新人
	UpdateBy *string `json:"update_by"`
	// 删除时间
	DeleteAt *time.Time `json:"delete_at"`
	// 删除人
	DeleteBy *string `json:"delete_by"`
	// 是否删除
	IsDelete bool `json:"is_delete"`
	// 备注
	Remark *string `json:"remark"`
}
