// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 渣土车工号牌制作订单表
type MuckTruckWorkerIDCardOrders struct {
	// 按指定方法生成                                               ( 主键                       )
	ID int64 `json:"id"`
	// 渣土车工号牌制作订单外部编码，由golang程序生成的xid，暴露到外部使用 ( 联合主键                   )
	MuckTruckWorkerOrdersID string `json:"muck_truck_worker_orders_id"`
	// vehicle_info 车辆信息表 的vehicle_id                     (                            )
	VehicleID string `json:"vehicle_id"`
	// muck_truck_preview_number  渣土车车辆预编号表的id        (                            )
	PreviewNumberID string `json:"preview_number_id"`
	// 创建时间                                                     (                            )
	CreatedAt time.Time `json:"created_at"`
	// 创建人                                                       ( system_user表的user_id )
	CreatedBy string `json:"created_by"`
	// 修改时间                                                     (                            )
	UpdatedAt *time.Time `json:"updated_at"`
	// 修改人                                                       ( system_user表的user_id )
	UpdatedBy *string `json:"updated_by"`
	// 删除时间                                                     (                            )
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人                                                       ( system_user表的user_id )
	DeletedBy *string `json:"deleted_by"`
}
