// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 渣土车车辆预编号表
type MuckTruckPreviewNumber struct {
	// 按指定方法生成                                               ( 主键                       )
	ID int64 `json:"id"`
	// 渣土车车辆预编号外部编码，由golang程序生成的xid，暴露到外部使用 ( 联合主键                   )
	MuckTruckPreviewNumberID string `json:"muck_truck_preview_number_id"`
	// vehicle_info 车辆信息表 的vehicle_id
	VehicleID string `json:"vehicle_id"`
	// 预编号
	SvnNumber *string `json:"svn_number"`
	// 登记时间
	RegistrationTime *string `json:"registration_time"`
	// 确认人                                                       ( system_user表的user_id )
	Confirmor *string `json:"confirmor"`
	// 确认时间
	ConfirmTime *time.Time `json:"confirm_time"`
	// 确认状态
	ConfirmStatus *int `json:"confirm_status"`
	// 前车牌
	FrontLicensePlate *string `json:"front_license_plate"`
	// 后车牌
	RearLicensePlate *string `json:"rear_license_plate"`
	// 侧车牌
	SideLicensePlate *string `json:"side_license_plate"`
	// 原编号
	OriginalNumber *string `json:"original_number"`
	// 是否自动审核
	IsReviewAutomatically *bool `json:"is_review_automatically"`
	// 制作状态
	ProductionStatus *int `json:"production_status"`
	// 制作时间
	ProductionTime *time.Time `json:"production_time"`
	// 制作中时间
	MarkingTime *time.Time `json:"marking_time"`
	// 制作次数
	ProductionTimes *int `json:"production_times"`
	// 提交制牌厂时间
	SubmitProductionTime *time.Time `json:"submit_production_time"`
	// 联系人
	ContactPerson *string `json:"contact_person"`
	// 联系电话
	ContactPhone *string `json:"contact_phone"`
	// 工号牌颜色（green.绿色 yellow.黄色）
	WorkNumberPlateColor *string `json:"work_number_plate_color"`
	// 初次登记日期
	InitialRegistrationDate *time.Time `json:"initial_registration_date"`
	// 违法未处理数
	UnlawfulViolationNumber *int `json:"unlawful_violation_number"`
	// 是否登记销售订单
	IsRegisterSaleOrder *bool `json:"is_register_sale_order"`
	// 备注
	Remarks *string `json:"remarks"`
	// 是否删除
	IsDeleted *bool `json:"is_deleted"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人                                                       ( system_user表的user_id )
	CreatedBy string `json:"created_by"`
	// 修改时间
	UpdatedAt *time.Time `json:"updated_at"`
	// 修改人                                                       ( system_user表的user_id )
	UpdatedBy *string `json:"updated_by"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人                                                       ( system_user表的user_id )
	DeletedBy *string `json:"deleted_by"`
}
