// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 车辆新增记录
type VehicleIncrementRecord struct {
	// 按指定方法生成                                  ( 主键                                 )
	ID int64 `json:"id"`
	// 外部编码，由golang程序生成的xid，暴露到外部使用 ( 联合主键                             )
	IncrementRecordID string `json:"increment_record_id"`
	// vehicle_info 车辆信息表 的vehicle_id
	VehicleID string `json:"vehicle_id"`
	// 所在企业id                                      ( enterprise_info表的enterprise_id )
	EnterpriseID *string `json:"enterprise_id"`
	// 自编号
	SelfNumber *string `json:"self_number"`
	// 操作类型
	OperationType *string `json:"operation_type"`
	// 车牌号
	LicensePlateNumber *string `json:"license_plate_number"`
	// 单位名称
	EnterpriseName *string `json:"enterprise_name"`
	// 地区
	Area *string `json:"area"`
	// 原编号
	OriginalNumber *string `json:"original_number"`
	// 运营商                                          ( enterprise_info表的enterprise_id )
	Operator *string `json:"operator"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人                                          ( system_user表的user_id           )
	CreatedBy string `json:"created_by"`
	// 修改时间
	UpdatedAt *time.Time `json:"updated_at"`
	// 修改人                                          ( system_user表的user_id           )
	UpdatedBy *string `json:"updated_by"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人                                          ( system_user表的user_id           )
	DeletedBy *string `json:"deleted_by"`
}
