enable: true
caches:
  department:
    enablePkCache: true
    enableListCache: true
    enableAggregateCache: true
    pkCacheTimeout: 30m
    listCacheTimeout: 30m
    aggregateCacheTimeout: 30m
    notExistRecordTimeout: 30s
defaultCache:
  enablePkCache: true
  pkCacheTimeout: 30m
  notExistRecordTimeout: 30s
