enable: true
caches:
  department:
    enablePkCache: true
    enableListCache: true
    enableAggregateCache: true
    pkCacheTimeout: 30m
    listCacheTimeout: 30m
    aggregateCacheTimeout: 30m
defaultCache:
  enablePkCache: true
  enableListCache: false
  enableAggregateCache: false
  pkCacheTimeout: 30m
