server:
  host: 0.0.0.0
  port: 8080

app:
  name: vehicle_supervision

db:
  master:
    host: "192.168.3.132"
    port: 5432
    username: "postgres"
    password: "root"
    dbname: "vehicle_1"
    sslmode: "disable"
    timezone: "Asia/Shanghai"
  slaves:
    -
      host: "192.168.3.133"
      port: 5432
      username: "postgres"
      password: "root"
      dbname: "vehicle_1"
      sslmode: "disable"
      timezone: "Asia/Shanghai"
  pool:
    maxIdleConn: 10
    maxOpenConn: 100
    maxLifeTime: 30m

redis:
  addresses:
    - "192.168.3.132:7001"
    - "192.168.3.132:7002"
    - "192.168.3.132:7003"
    - "192.168.3.132:7004"
    - "192.168.3.132:7005"
    - "192.168.3.132:7006"
  pool:
    minIdle: 5
    maxActive: 10
    idleTimeout: 10m
log:
  path: "runtime/logs"
  level: "debug"
  mode: "all" #日志模式,console,file,all
gql:
  cacheConfigFile: "config/gqlcache.yaml"