// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 驾驶员违法核实记录表
type DriverPeccancyCheck struct {
	// 按指定方法生成 ( 主键                                 )
	ID int64 `json:"id"`
	// 违章车辆id     ( vehicle_info表的vehicle_id       )
	VehicleID *string `json:"vehicle_id"`
	// 违章驾驶员id   ( driver_info表的driver_id         )
	DriverID *string `json:"driver_id"`
	// 所在企业id     ( enterprise_info表的enterprise_id )
	EnterpriseID *string `json:"enterprise_id"`
	// 创建时间       (                                      )
	CreatedAt time.Time `json:"created_at"`
	// 创建人         ( system_user表的user_id           )
	CreatedBy string `json:"created_by"`
	// 修改时间       (                                      )
	UpdatedAt *time.Time `json:"updated_at"`
	// 修改人         ( system_user表的user_id           )
	UpdatedBy *string `json:"updated_by"`
	// 删除时间       (                                      )
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人         ( system_user表的user_id           )
	DeletedBy *string `json:"deleted_by"`
}
