// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 驾驶员黑名单申请
type DriverBlacklistApply struct {
	// ID
	ID int64 `json:"id"`
	// 驾驶员黑名单申请ID
	ApplyID string `json:"apply_id"`
	// 驾驶员ID
	DriverID string `json:"driver_id"`
	// 申请原因
	ApplyReason *string `json:"apply_reason"`
	// 黑名单类型
	BlacklistType *int `json:"blacklist_type"`
	// 状态（1：待交警大队审批2：待交警支队审批，3：退回，4：完成
	State *int `json:"state"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 创建人
	CreateBy *string `json:"create_by"`
	// 更新时间
	UpdateAt *time.Time `json:"update_at"`
	// 更新人
	UpdateBy *string `json:"update_by"`
	// 删除时间
	DeleteAt *time.Time `json:"delete_at"`
	// 删除人
	DeleteBy *string `json:"delete_by"`
	// 是否删除
	IsDelete bool `json:"is_delete"`
}
