// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 企业黑名单预警表
type EnterpriseBlacklistAlarm struct {
	// ID
	ID int64 `json:"id"`
	// 企业黑名单预警表ID
	AlarmID string `json:"alarm_id"`
	// 企业ID
	EnterpriseID string `json:"enterprise_id"`
	// 类型
	Type int `json:"type"`
	// 年份
	Year int `json:"year"`
	// 企业的车辆是否10%以上的车进入黑名单
	IsBlack bool `json:"is_black"`
	// 企业是否连续两个季度违规记分排名前十
	IsRank bool `json:"is_rank"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 创建人
	CreatedBy *string `json:"created_by"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at"`
	// 更新人
	UpdatedBy *string `json:"updated_by"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at"`
	// 删除人
	DeletedBy *string `json:"deleted_by"`
	// 是否删除
	IsDeleted *bool `json:"is_deleted"`
}
