// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// 车辆黑名单预警
type VehicleBlacklistAlarm struct {
	// ID
	ID int64 `json:"id"`
	// 车辆黑名单警告ID
	AlarmID string `json:"alarm_id"`
	// 车辆ID
	VehicleID string `json:"vehicle_id"`
	// 车牌号
	LicensePlateNumber *string `json:"license_plate_number"`
	// 年份
	Year *int `json:"year"`
	// 扣分数量
	ScoreNum *int `json:"score_num"`
	// 扣分次数
	ScoreCount *int `json:"score_count"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 创建人
	CreateBy *string `json:"create_by"`
	// 更新时间
	UpdateAt *time.Time `json:"update_at"`
	// 更新人
	UpdateBy *string `json:"update_by"`
	// 删除时间
	DeleteAt *time.Time `json:"delete_at"`
	// 删除人
	DeleteBy *string `json:"delete_by"`
	// 是否删除
	IsDelete bool `json:"is_delete"`
}
